"""empty message

Revision ID: 010136508137
Revises: 18a42d53ee9d
Create Date: 2023-06-11 16:29:14.755748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010136508137'
down_revision = '18a42d53ee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('person_type')

    # ### end Alembic commands ###
